  GNU nano 6.2                                                                                create_swarm.yml
---
- name: Initialize and Join Docker Swarm
  hosts: master
  become: yes
  tasks:

    - name: Leave Swarm if Already Joined
      command: docker swarm leave -f
      ignore_errors: yes

    - name: Create primary swarm manager
      shell: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}

    - name: Get docker swarm manager ip
      copy:
        content: '{{ ansible_default_ipv4.address }}'
        dest: '/tmp/dsm_ip'

    - name: Get docker swarm manager token
      shell: docker swarm join-token -q manager
      register: swarm_manager_token
    - copy:
        content: '{{ swarm_manager_token.stdout }}'
        dest: '/tmp/dsm_mt'

    - name: Get docker swarm worker token
      shell: docker swarm join-token -q worker
      register: swarm_worker_token
    - copy:
        content: '{{ swarm_worker_token.stdout }}'
        dest: '/tmp/dsm_wt'


- hosts: workers
  become: yes
  tasks:
    - name: Leave Swarm if Already Joined
      command: docker swarm leave -f
      ignore_errors: yes

    - name: Join the swarm
      shell: "docker swarm join --token {{ lookup('file', '/tmp/dsm_mt') }} {{ lookup('file', '/tmp/dsm_ip') }}:2377"
      retries: 5
      delay: 5


