---
- name: Setup pre-requisites
  hosts: all
  become: yes
  roles:
    - configure-hosts-hostname

- name: Install docker 
  become: yes
  hosts: all
  roles:
    - install-docker

- name: Setting firewall
  hosts: all
  become: yes
  roles:
    - setting-firewall

- name: initialize docker swarm (master)
  hosts: master
  become: yes
  roles:
    - docker-swarm-manager

- name: add workers to the swarm
  hosts: workers
  become: yes
  roles:
    - docker-swarm-workers
