---
- name: Setup pre-requisites
  hosts: all
  become: yes
  roles:
    - configure-hosts-hostname

- name: Install docker 
  become: yes
  hosts: all
  roles:
    - install-docker
    
- name: Confirm before change Setting Firewall
  hosts: all
  pause:
    prompt: "Do you want to change Setting Firewall ? (yes/no)"
  register: confirm_setting_firewall
  
- name: Setting firewall
  hosts: all
  become: yes
  roles:
    - setting-firewall
  when: confirm_setting_firewall.user_input == 'yes'

- name: initialize docker swarm (master)
  hosts: master
  become: yes
  roles:
    - docker-swarm-manager

- name: add workers to the swarm
  hosts: workers
  become: yes
  roles:
    - docker-swarm-workers
