---
- name: Update /etc/hosts file
  hosts: all
  become: yes

  tasks:
    - name: Append hosts template to /etc/hosts if not exist
      lineinfile:
        path: /etc/hosts
        line: "{{ lookup('template', 'hosts.j2') }}"
        insertafter: EOF
      notify: Reload hosts file

  handlers:
    - name: Reload hosts file
      command: systemctl restart systemd-resolved
      ignore_errors: yes
