---
- name: Add entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ inventory_hostname }} {{ hostvars[inventory_hostname]['ansible_host'] | default(inventory_hostname) }}"
    
- name: Change 127.0.1.1 entry in /etc/hosts
  replace:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1 .*'
    replace: '127.0.1.1 {{ inventory_hostname }}'

- name: "Configure hostname"
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    
- name: Append hosts template to /etc/hosts if not exist
  lineinfile:
    path: /etc/hosts
    line: "{{ lookup('template', './templates/hosts.j2') }}"
    insertafter: EOF

- name: Reload hosts file
  command: systemctl restart systemd-resolved
  ignore_errors: yes
