---
- name: Confirm before change Setting Firewall
  pause:
    prompt: "Do you want to change Setting Firewall ? (yes/no)"
  register: confirm_setting_firewall

- name: Install UFW (Ubuntu)
  apt:
    name: ufw
  when: ansible_distribution == 'Ubuntu' and confirm_setting_firewall.user_input == 'yes'

- name: Install firewalld (CentOS)
  yum:
    name: firewalld
  when: ansible_distribution == 'CentOS' and confirm_setting_firewall.user_input == 'yes'

- name: Start and enable UFW or firewalld service
  systemd:
    name: "{{ 'ufw' if ansible_distribution == 'Ubuntu' else 'firewalld' }}"
    state: started
    enabled: yes
  when: confirm_setting_firewall.user_input == 'yes'

- name: Allow SSH (Port 22) through UFW or firewalld (CentOS)
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_distribution == 'CentOS' and confirm_setting_firewall.user_input == 'yes'

- name: Allow SSH (Port 22) through UFW (Ubuntu)
  ufw:
    rule: allow
    port: '22'
    proto: tcp
      when: ansible_distribution == 'Ubuntu' and confirm_setting_firewall.user_input == 'yes'

    - name: Enable UFW (Ubuntu)
      ufw:
        state: enabled
      when: ansible_distribution == 'Ubuntu' and confirm_setting_firewall.user_input == 'yes'
